// Deterministic mechanical adaptation of the pinned Studio stylesheet.
import fs from 'node:fs';
import postcss from 'postcss';
const root=postcss.parse(fs.readFileSync('features/jieum/studio-baseline.css','utf8'));
root.walkAtRules('import',rule=>rule.remove());
// Preserve every layout selector while retiring Studio's sub-12px typography.
root.walkDecls(/^(?:font|font-size)$/,decl=>{decl.value=decl.value.replace(/(?<![\w.])([\d.]+)px/g,(whole,size)=>Number(size)<12?'12px':whole)});
const animations=new Map();root.walkAtRules(/keyframes$/,rule=>{const name=rule.params.trim();animations.set(name,'jieum-'+name);rule.params='jieum-'+name});
root.walkDecls(/animation(?:-name)?$/,decl=>{for(const [old,name]of animations)decl.value=decl.value.replace(new RegExp('(?<![\\w-])'+old+'(?![\\w-])','g'),name)});
root.walkRules(rule=>{
  if(rule.parent.type==='atrule'&&/keyframes$/.test(rule.parent.name))return;
  rule.selectors=rule.selectors.map(selector=>{
    // Replace element selectors, never class fragments such as .panel-body.
    const scoped=selector.replace(/:root\b/g,'.jieum-editor').replace(/(^|[\s>+~])(?:html|body)(?=$|[\s.#[:>+~])/g,'$1.jieum-editor');
    return scoped.startsWith('.jieum-editor')?scoped:'.jieum-editor '+scoped;
  });
});
fs.writeFileSync('features/jieum/jieum-scoped.css','/* Generated by scripts/scope-jieum.mjs. No global selectors. */\n'+root.toString());
