import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import JSZip from 'jszip';
import {makeProjectForPackageTarget,blankStoryEvent,validateProject,normalizeProject} from '../../features/jieum/studio-model';
import {canonDesign,compileCanonDesign,canonIssues,emptyCanonEvent} from '../../features/jieum/canon-design';
import {eventDesign} from '../../features/jieum/cortex-event-design';
import {exportScenarioPack,extractStudioProjectFromPackage} from '../../features/jieum/studio-export';
import {HeadlessCortex,makeModel} from '../cortex/harness.mjs';

function fixture(){const p=makeProjectForPackageTarget('cortex','intelligent_canon',false);p.title='개편 검증';p.genre='학원';p.startLocation='교실';p.player.name='윤서';p.events=['A','B','C','D'].map(id=>{const e={...blankStoryEvent(),id,name:id,required:true,description:'윤서가 교실에서 편지를 확인한다.'};return {...e,cortexDesign:{...eventDesign(e),occurrenceEnabled:false,closureConditions:[{id:id+'-goal',text:'윤서가 편지를 확인한다.'}]}}});const d=canonDesign(p);d.openingSituation='교실에서 편지를 발견했다.';d.mode='unlock';d.routes=[{id:'r1',name:'첫 이야기'},{id:'r2',name:'두 번째 이야기'}];d.events=Object.fromEntries(p.events.map((e,i)=>[e.id,{...emptyCanonEvent(i<2?'r1':'r2'),ending:i===1||i===3,authorComment:i===2?'새로운 시점에서 시작합니다.':''}]));d.stats=[{id:'trust',label:'신뢰',characterId:p.player.id,initial:0,minimum:0,maximum:100,unit:'',visible:false,mode:'event',increaseWhen:'',decreaseWhen:''},{id:'seal',label:'령주',characterId:p.player.id,initial:3,minimum:0,maximum:5,unit:'획',visible:true,mode:'resource',increaseWhen:'양도받으면 늘어난다',decreaseWhen:'사용하면 줄어든다'}];d.events.A.effects=[{id:'help',criterion:'편지를 확인한다.',statId:'trust',amount:10}];d.events.C.effects=[{id:'later',criterion:'부탁을 들어준다.',statId:'trust',amount:20}];p.canonDesign=d;return p;}
async function runtime(){const p=fixture(),output=await exportScenarioPack(p,false),zip=await JSZip.loadAsync(await output.blob.arrayBuffer()),files:Record<string,any>={};for(const [path,f] of Object.entries(zip.files))if(path.endsWith('.json')&&!path.startsWith('studio/'))files[path]=JSON.parse(await f.async('string'));const ctx:any=vm.createContext({console,TextEncoder,TextDecoder,URL,crypto,structuredClone,setTimeout,clearTimeout,performance,AbortController});const scripts=[...fs.readFileSync('vendor/cortex/Cortex_v1.42.0.html','utf8').matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)];for(const i of [0,1,3])vm.runInContext(scripts[i][1],ctx);const session=ctx.CortexNexusBridge.adaptPackage(files),sc=ctx.CortexNexusBridge.toCortexScenario(session);ctx.CortexJieum.initialize(sc);return {p,output,files,ctx,sc};}
test('normal completed turns reach the ending and unlock the next story',async()=>{
 const {sc}=await runtime(),model=makeModel({writer:()=> '윤서는 교실에서 편지를 확인했다. 종이를 책상에 내려놓았다.\n\n이제 확인은 끝났고 다음 방으로 향할 준비가 되었다.',eventVerdict:(p:any)=>({requirements:p.requirements.map((r:any)=>({requirementRef:r.ref,status:'MET',reason:'확인 완료'})),choices:Object.fromEntries((p.choices||[]).map((r:any)=>[r.key,'SATISFIED'])),resources:{r0:{status:'KNOWN',delta:0,evidence:''}},earlyClosure:{goalsMet:'YES',sceneActionSettled:'YES',sceneSettled:'YES',handoffReady:'YES',reason:'확인과 장면 종료'}})});
 const app=await new HeadlessCortex({initialScenario:sc,standalonePath:'vendor/cortex/Cortex_v1.42.0.html',model}).open();try{app.api._setSettings({apiKey:'fixture-only',typingSpeed:'instant'});for(let i=0;i<8&&!app.scenario.runtime.branchEndingState?.ending;i++)await app.turn('편지를 확인하고 장면을 마무리한다.');assert.equal(app.scenario.runtime.branchEndingState?.ending?.terminalEventId,'B');await app.api._nextJieumRoute();assert.equal(app.scenario.event.id,'C');assert.ok(app.scenario.runtime.jieum.archives[0].turns.length>=2);}finally{app.close();}
});
test('image triggers use the source event and fire once at the selected moment',async()=>{const {ctx,sc}=await runtime();sc.runtime.packageContract.imageTriggers=['event_start','event_condition_met','event_success'].map((triggerType,i)=>({id:'img'+i,enabled:true,once:true,sourceId:'A',triggerType,customCondition:'A-goal',attachedImages:[{assetPath:'assets/test.png'}]}));const first:any={id:'image1',sourceEventId:'A',metrics:{unifiedAdjudication:{requirements:[{requirementRef:'A:A-goal',status:'MET'}]}}};assert.equal(ctx.CortexJieum.images(sc,first,{id:'A'}).length,2);sc.runtime.packageV15.completedEventIds=['A'];assert.equal(ctx.CortexJieum.images(sc,{id:'image2',sourceEventId:'A'}, {id:'A'}).length,1);assert.equal(ctx.CortexJieum.images(sc,{id:'image3',sourceEventId:'A'}, {id:'A'}).length,0);});
test('canon authoring compiles, validates and round-trips without changing originals',async()=>{const p=fixture(),before=JSON.stringify(p),compiled=compileCanonDesign(p);assert.equal(compiled.package15.branchEnding.choiceRecords.length,2);assert.deepEqual(canonIssues(p),[]);assert.deepEqual(validateProject(p).filter(x=>x.severity==='error'),[]);const {output}=await runtime();const imported=await extractStudioProjectFromPackage(output.blob);assert.deepEqual(normalizeProject(imported.project).canonDesign,p.canonDesign);assert.equal(JSON.stringify(p),before);});
test('route locks, endings, start reset and archive survive serialized restore',async()=>{const {ctx,sc}=await runtime(),j=ctx.CortexJieum;assert.equal(sc.event.id,'A');assert.equal(sc.event.nextEvent.id,'B');assert.equal(sc.event.nextEvent.nextEvent,null);assert.throws(()=>j.nextRoute(sc,[]),/LOCKED/);sc.runtime.branchEndingState={choices:{},decisions:{},flagBase:{},ending:{terminalEventId:'B'}};sc.runtime.jieum.resourceValues.seal=1;const next=j.nextRoute(sc,[{id:'read',text:'첫 이야기 본문'}]);assert.equal(next.event.id,'C');assert.equal(next.runtime.jieum.resourceValues.seal,3);assert.equal(next.runtime.jieum.seen[0],'r1');assert.equal(next.runtime.jieum.archives[0].turns.length,1);const restored=JSON.parse(JSON.stringify(next));j.initialize(restored);assert.equal(restored.event.id,'C');assert.equal(restored.runtime.jieum.routeIndex,1);assert.equal(restored.runtime.packageV15.branchEnding.records.length,1);});
test('resources apply once, accept increases and reject ambiguous or out of bounds batches',async()=>{const {ctx,sc}=await runtime(),j=ctx.CortexJieum,turn={id:'t1'};j.stage(sc,{r0:{status:'KNOWN',delta:-1,evidence:'령주를 1획 사용했다.'}},turn.id,'윤서는 령주를 1획 사용했다.');j.commit(sc,turn);j.commit(sc,turn);assert.equal(j.values(sc).seal,2);j.stage(sc,{r0:{status:'KNOWN',delta:2,evidence:'2획을 받았다.'}},'t2','윤서는 2획을 받았다.');j.commit(sc,{id:'t2'});assert.equal(j.values(sc).seal,4);j.stage(sc,{r0:{status:'KNOWN',delta:2,evidence:'2획을 받았다.'}},'t3','윤서는 2획을 받았다.');j.commit(sc,{id:'t3'});assert.equal(j.values(sc).seal,4);assert.equal(sc.runtime.jieum.resourceStatus,'UNCONFIRMED');});
test('a future event score does not make a current numeric branch unknown',async()=>{const {ctx,sc}=await runtime(),b=ctx.CortexBranchEnding;b.record(sc,b.pending(sc),{c0:'SATISFIED'},'t1');assert.equal(b.evaluate(sc,{kind:'flag_at_least',flagId:'trust',value:10}),true);});
test('missing route endings, cross-route links and deleted stat refs fail validation',()=>{const p=fixture();p.canonDesign!.events.A.branching=true;p.canonDesign!.events.A.fallbackEventId='C';p.canonDesign!.events.A.branches=[{id:'bad',kind:'stat',criterion:'',statId:'deleted',threshold:5,comparison:'gte',nextEventId:'D'}];assert.ok(canonIssues(p).length>=2);});
test('one verdict call updates a resource and authored score; rewind restores both',async()=>{
 const {sc}=await runtime();const model=makeModel({writer:()=> '윤서는 교실에서 편지를 확인했다. 령주를 1획 사용했다.\n\n창밖을 바라보며 다음 답장을 기다렸다.',eventVerdict:(p:any)=>({requirements:p.requirements.map((r:any)=>({requirementRef:r.ref,status:'MET',reason:'본문 확인'})),choices:Object.fromEntries((p.choices||[]).map((r:any)=>[r.key,'SATISFIED'])),resources:{r0:{status:'KNOWN',delta:-1,evidence:'령주를 1획 사용했다.'}},earlyClosure:{goalsMet:'YES',sceneActionSettled:'NO',sceneSettled:'NO',handoffReady:'YES',reason:'계속'}})});
 const app=await new HeadlessCortex({initialScenario:sc,standalonePath:'vendor/cortex/Cortex_v1.42.0.html',model}).open();try{app.api._setSettings({apiKey:'fixture-only',typingSpeed:'instant'});const t=await app.turn('편지를 확인한다.');assert.equal(t.status,'COMMITTED');assert.equal(app.win.CortexJieum.values(app.scenario).seal,2);assert.equal(app.win.CortexJieum.values(app.scenario).trust,10);assert.equal(model.calls.filter((c:any)=>c.kind==='eventVerdict').length,1);assert.equal(model.calls.filter((c:any)=>c.kind==='eventVerdict')[0].payload.currentTurnProse.includes('령주'),true);app.win.confirm=()=>true;await app.api._rewind();assert.equal(app.win.CortexJieum.values(app.scenario).seal,3);assert.equal(app.win.CortexJieum.values(app.scenario).trust,0);}finally{app.close()}
});
test('full Cortex import preserves route contract and starts the next route',async()=>{const {sc}=await runtime();const app=await new HeadlessCortex({initialScenario:sc,standalonePath:'vendor/cortex/Cortex_v1.42.0.html',model:makeModel()}).open();try{assert.equal(app.scenario.runtime.jieum.routeIndex,0);app.scenario.runtime.branchEndingState={choices:{},decisions:{},flagBase:{},ending:{terminalEventId:'B'}};await app.api._nextJieumRoute();assert.equal(app.scenario.event.id,'C');assert.equal(app.turns.length,0);await app.api.persist();const saved=app.close();(app as any).didClose=true;const reopened=await new HeadlessCortex({...saved,initialScenario:sc,standalonePath:'vendor/cortex/Cortex_v1.42.0.html',model:makeModel()}).open();try{assert.equal(reopened.scenario.event.id,'C');assert.equal(reopened.scenario.runtime.jieum.routeIndex,1);}finally{reopened.close()}}finally{if(!(app as any).didClose)app.close()}});
test('trigger placement uses only a unique literal quote from the current beat',async()=>{
 const {ctx,sc}=await runtime(),j=ctx.CortexJieum,prose='문이 열렸다. 편지를 건넸다. 그들은 기다렸다.';
 const turn={text:prose},trigger={triggerType:'event_condition_met',outputPosition:'after_scene'};
 const valid=j.imageAnchor(turn,trigger,'편지를 건넸다.');assert.equal(valid.offset,prose.indexOf('편지를 건넸다.')+'편지를 건넸다.'.length);assert.equal(valid.kind,'PUBLIC_QUOTE');
 assert.equal(j.imageAnchor(turn,trigger,'비공개 미래 장면').kind,'UNRESOLVED');assert.equal(j.imageAnchor({text:prose+prose},trigger,'편지를 건넸다.').kind,'UNRESOLVED');
 sc.runtime.packageContract.imageTriggers=[{id:'image',sourceId:sc.event.id,triggerType:'event_condition_met',customCondition:'goal',enabled:true}];
 const request:any={},transport:any={schema:{properties:{},required:[]}};j.extendImages(request,transport,sc,prose);assert.equal(request.currentImageTurnProse,prose);assert.equal(request.imageMoments.length,1);assert.ok(transport.schema.properties.imageMoments);assert.equal(transport.schema.properties.imageMoments.properties.image0.type,'string');
});
