import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import {characterHeight,projectStature,stageReferenceHeight} from '../../public/vn-runtime/vn-stature.mjs';
const root=path.resolve('outputs/portrait-audit-20261003'),m=JSON.parse(await fs.readFile(path.join(root,'manifest.json'),'utf8')),r=JSON.parse(await fs.readFile(path.join(root,'results/measurements.json'),'utf8'));
if(r.errors.length)console.warn('Execution errors remain:',r.errors.length);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=s=>'"'+String(s??'').replaceAll('"','""')+'"';const round=n=>Number.isFinite(n)?Math.round(n*100)/100:null;
const target=r.metrics.filter(x=>x.isTarget),base=target.filter(x=>x.variant==='generated'&&x.mode==='group-1');
const byKey=new Map(m.rows.map(x=>[x.key,x]));
const invariance=[];for(const x of target.filter(x=>x.mode==='group-1'&&['half','padded','bust','crown-cut','chroma'].includes(x.variant))){const b=base.find(b=>b.key===x.key&&String(b.viewport)===String(x.viewport));if(!b)continue;const aw=x.manual?.faceWidthPx||x.estimatedExposedFaceWidthPx,bw=b.manual?.faceWidthPx||b.estimatedExposedFaceWidthPx;const e=x.manual?.eye||x.estimatedEye,be=b.manual?.eye||b.estimatedEye;invariance.push({key:x.key,variant:x.variant,viewport:x.viewport.join('x'),faceWidthChangePct:bw?round((aw/bw-1)*100):null,eyeShiftPx:e&&be?round(e.y-be.y):null,manual:!!x.manual,frameStatus:x.frameStatus});}
// Effective scale compares the same source pixels, independently of a face detector.
// A half-resolution pixel spans two original pixels, so its scale is divided by two.
for(const x of invariance){const row=target.find(t=>t.key===x.key&&t.variant===x.variant&&t.mode==='group-1'&&t.viewport.join('x')===x.viewport);const b=base.find(t=>t.key===x.key&&t.viewport.join('x')===x.viewport);x.effectiveScaleChangePct=round((row.screenPixelScale*(x.variant==='half'?.5:1)/b.screenPixelScale-1)*100);}
const groups=new Map();for(const x of r.metrics){const k=[x.caseKey,x.viewport.join('x'),x.mode,x.variant].join('|');const a=groups.get(k)||[];a.push(x);groups.set(k,a);}
const placement=[...groups.entries()].filter(([,a])=>a.length>1).map(([key,a])=>({key,virtualGroundRangePx:round(Math.max(...a.map(x=>x.virtualGroundY))-Math.min(...a.map(x=>x.virtualGroundY))),pixelsPerCmRange:round(Math.max(...a.map(x=>x.slotHeight/x.heightCm))-Math.min(...a.map(x=>x.slotHeight/x.heightCm)))}));
const soloMulti=[];for(const x of target.filter(x=>x.variant==='generated'&&x.mode!=='group-1')){const b=base.find(b=>b.key===x.key&&String(b.viewport)===String(x.viewport));if(b)soloMulti.push({key:x.key,viewport:x.viewport.join('x'),mode:x.mode,heightChangePx:round(x.slotHeight-b.slotHeight),scaleChangePct:round((x.screenPixelScale/b.screenPixelScale-1)*100),eyeShiftPx:round((x.manual?.eye||x.estimatedEye)?.y-(b.manual?.eye||b.estimatedEye)?.y)});}
const genAudits=r.audits.filter(x=>x.variant==='generated'),counts={};for(const a of genAudits)counts[a.check.code]=(counts[a.check.code]||0)+1;
const works=[...new Set(m.rows.map(x=>x.work))].map(work=>{const rows=m.rows.filter(x=>x.work===work),eligible=rows.filter(x=>m.eligible.includes(x.key));return{work,title:rows[0].title,characters:rows.length,references:eligible.length,primaryBalancedSample:eligible.slice(0,3).map(x=>x.key),generated:m.generation.generated.filter(x=>eligible.some(y=>y.key===x.key)).length};});
const fixtures=m.rows.map(row=>{const roster=m.rows.filter(x=>x.work===row.work).map(x=>x.person),ref=stageReferenceHeight(roster);return{key:row.key,name:row.person.name,authoredHeightSource:row.heightSource,heightCm:characterHeight(row.person),referenceCm:ref,projection:projectStature(row.person,ref)};});
const measurements={requested:50,availableUniqueWithReference:m.eligible.length,unexecutedCharacters:50-m.eligible.length,generated:m.generation.generated.length,renderedRows:r.metrics.length,audits:r.audits.length,executionErrors:r.errors.length,frameChecks:counts,calibrationMethods:Object.fromEntries([...new Set(genAudits.map(x=>x.method||'none'))].map(k=>[k,genAudits.filter(x=>(x.method||'none')===k).length])),headClipped:base.filter(x=>x.headClipped).length,maxGroundSpreadPx:Math.max(...placement.map(x=>x.virtualGroundRangePx)),maxSoloMultiScaleChangePct:Math.max(...soloMulti.map(x=>Math.abs(x.scaleChangePct))),works,invariance,placement,soloMulti};
await fs.writeFile(path.join(root,'results/analysis.json'),JSON.stringify(measurements,null,2));await fs.writeFile(path.join(root,'results/height-fixtures.json'),JSON.stringify(fixtures,null,2));
const columns=['key','variant','viewport','mode','heightCm','referenceCm','statureScale','slotHeight','screenPixelScale','estimatedExposedFaceWidthPx','manualFaceWidthPx','manualEyeY','crownY','drawnBottomY','virtualGroundY','headClipped','sourceHeadTruncated','frameStatus'];
const lines=[columns.map(q).join(','),...target.map(x=>{const row={...x,viewport:x.viewport.join('x'),manualFaceWidthPx:x.manual?.faceWidthPx,manualEyeY:x.manual?.eye?.y};return columns.map(k=>q(typeof row[k]==='number'?round(row[k]):row[k])).join(',');})];await fs.writeFile(path.join(root,'results/measurements.csv'),'\uFEFF'+lines.join('\n'));
await fs.writeFile(path.join(root,'results/invariance.csv'),'\uFEFF'+['key,variant,viewport,effectiveScaleChangePct,faceWidthChangePct,eyeShiftPx,manual,frameStatus',...invariance.map(x=>[x.key,x.variant,x.viewport,x.effectiveScaleChangePct,x.faceWidthChangePct,x.eyeShiftPx,x.manual,x.frameStatus].map(q).join(','))].join('\n'));
const paths=['package.json','public/cortex-vn-camera.mjs','public/vn-runtime/vn-sprite.mjs','public/vn-runtime/vn-stature.mjs','public/vn-runtime/vn-chroma.mjs','public/vn-runtime/vn-stage.mjs','public/vn-runtime/vn-reader.css','public/vn-runtime/vn.css','public/cortex-vn-layout.css','scripts/port-visual-novel.mjs'];
const hashes=[];for(const p of paths)hashes.push({path:p,sha256:crypto.createHash('sha256').update(await fs.readFile(p)).digest('hex')});
const provenance={version:JSON.parse(await fs.readFile('package.json','utf8')).version,head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),productionDiff:execFileSync('git',['diff','--','public','scripts','package.json'],{encoding:'utf8'}),hashes,visionSource:'../dancheong-visual-novel-site/public/vn-vision/1.0.1 (local copy)',imageGeneration:{tool:'conversation imagegen',calls:35,modelArgumentAvailable:false,requestedModel:'GPT 2.5 Flare',requestedReasoning:'low',actualModel:'NOT_EXPOSED_BY_TOOL',externalGenerationApis:0},existingTests:{command:'node --test tests/cortex/vn-camera-calibration.test.mjs tests/cortex/vn-entry-camera.test.mjs',passed:10,failed:0},run:{started:r.started,finished:r.finished,userAgent:r.userAgent},limitations:r.notes};
await fs.writeFile(path.join(root,'results/provenance.json'),JSON.stringify(provenance,null,2));
const manual=base.filter(x=>x.manual&&x.viewport[0]===1440).map(x=>({name:byKey.get(x.key).person.name,key:x.key,height:x.heightCm,face:round(x.manual.faceWidthPx),perCm:round(x.manual.faceWidthPx/x.heightCm),eye:round(x.manual.eye.y)}));
const table=(heads,rows)=>`<table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(a=>`<tr>${a.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>단청 v1.25.9 입상 검증 결과</title><style>body{max-width:1200px;margin:40px auto;padding:0 24px;background:#101c2b;color:#e9f0f7;font:16px/1.7 system-ui}h1,h2{line-height:1.25}h2{margin-top:42px;color:#9be3d3}a{color:#99c8ff}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:9px;border-bottom:1px solid #344960;text-align:left}img{max-width:100%;background:#192c3e}figure{margin:18px 0}small{color:#adbdce}.note{padding:18px;background:#223650;border-left:4px solid #e6bd75}details{padding:10px;border:1px solid #344960;margin:10px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style>
<h1>단청 v1.25.9 · 입상 비율 검증</h1><p>실행: ${esc(r.started)} → ${esc(r.finished)}<br>실제 보정 모듈과 운영 CSS를 그대로 사용하는 로컬 시뮬레이터.</p>
<h2>결론: 현재 비율 보정은 추가 수정이 필요합니다</h2><p>같은 162cm인 김다윤·백서현의 얼굴 폭이 약 <b>1.71배</b> 차이 납니다. 단독↔다인 배율은 유지되지만, 서로 다른 그림을 같은 카메라 거리로 맞추는 보정은 아직 불안정합니다. <a href="visual-review.txt">직접 검토한 실패·원인·권장 수정 순서</a></p>
<figure><img src="results/chronos-core__NPC_KIM_DAYUN--generated--1440x900--group-3.png" alt="김다윤이 같은 키의 백서현보다 매우 작게 표시된 실제 보정 결과"><figcaption>왼쪽 김다윤 162cm · 가운데 박은서 178cm · 오른쪽 백서현 162cm. 이번에 생성한 시험 입상입니다.</figcaption></figure>
<div class="note"><b>50명 검증 완료가 아닙니다.</b> 공개 패키지 5개는 중복 제외 46명이며, 내장 참조가 있는 인물은 35명입니다. 이 35명 모두 내장 이미지 도구로 입상을 생성했습니다. 나머지 15명분은 참조·인물 수 부족으로 미실행입니다. 김서연은 패키지와 사용자 지정 모두 164cm이며 수치 투영 검사에 포함했지만, 내장 그림이 없어 참조 이미지 비교는 미실행입니다.<br>도구가 모델명·추론 수준 선택 및 응답 메타데이터를 제공하지 않아 GPT 2.5 Flare / low 적용 여부는 확인할 수 없습니다.</div>
<h2>실행 범위와 결과</h2>${table(['항목','실측'],[['생성한 서로 다른 인물',measurements.generated],['입력 조건 검사',measurements.audits],['배치 측정행 (동반 인물 포함)',measurements.renderedRows],['최종 실행 오류',measurements.executionErrors],['생성본의 프레임 검사 코드',JSON.stringify(counts)],['보정 경로',JSON.stringify(measurements.calibrationMethods)],['생성본 단독 배치 상단 잘림',measurements.headClipped],['단독↔다인 최대 확대율 변화',measurements.maxSoloMultiScaleChangePct+'%'],['다인 가상 바닥 최대 차이',measurements.maxGroundSpreadPx+'px']])}
<p>1440×900 / 844×390 / 390×844. 단독·2인·3인. 내장 원본, 생성 입상, 해상도 1/2, 투명 여백 추가, 하단 44% 크롭, 상단 7.5% 크롭, 초록 매트 합성 후 실제 크로마 제거를 검사했습니다. 크롭·리사이즈는 동일 그림에 가한 결정적 시험 변형이며 새 인물로 집계하지 않았습니다.</p>
<h2>작품 분포</h2>${table(['작품','등록 인물','참조 있음','생성 완료'],works.map(w=>[w.title,w.characters,w.references,w.generated]))}<p>작품 간 비교의 균형 표본은 이미지가 있는 4개 작품에서 3명씩 12명입니다. 추가 23명은 확보 가능한 전체 표본을 확장 검사한 것이며, 작품 평균과 혼동하지 않아야 합니다.</p>
<h2>원본 조건에 따른 확대율 편차</h2><p>같은 그림의 실제 픽셀 확대율을 비교했습니다. 절반 해상도 조건은 원본 픽셀 크기로 환산합니다. 자동 얼굴 폭의 변화와 혼동하지 않도록 CSV에 effectiveScaleChangePct를 따로 저장했습니다.</p>${table(['조건','최대 절대 확대율 변화','±10% 초과 인물'],['half','padded','bust','crown-cut','chroma'].map(v=>{const a=invariance.filter(x=>x.variant===v&&x.viewport==='1440x900');return[v,Math.max(...a.map(x=>Math.abs(x.effectiveScaleChangePct)))+'%',a.filter(x=>Math.abs(x.effectiveScaleChangePct)>10).length+'/35'];}))}<p>±10%는 이상 사례를 찾기 위한 보고 구간이며 합격 기준은 아닙니다. 백서현의 하단 크롭에서는 확대율이 +249.07%, 약 3.49배가 됐습니다.</p>
<div class="grid"><figure><img loading="lazy" src="results/review-chronos-core__NPC_BAEK_SEOHYUN--generated-vs-bust--1440x900--group-1--before.png"><figcaption>백서현 · 생성 원본 보정</figcaption></figure><figure><img loading="lazy" src="results/review-chronos-core__NPC_BAEK_SEOHYUN--generated-vs-bust--1440x900--group-1--after.png"><figcaption>같은 그림의 하단만 자른 뒤 보정</figcaption></figure></div>
<h2>얼굴 크기 — 직접 확인한 표본</h2><p>1440×900 단독 배치. 생성 원본에서 눈 중심·얼굴 폭을 육안으로 기록한 근사값(원본 ±15px)입니다. 자동 얼굴 검출 결과를 정답으로 재사용하지 않았습니다. 얼굴 폭/cm은 비교 지표이며 모든 인물의 해부학적 얼굴 폭이 같아야 한다는 뜻은 아닙니다.</p>${table(['인물','키 cm','얼굴 폭 px','폭/키','눈높이 y'],manual.map(x=>[x.name,x.height,x.face,x.perCm,x.eye]))}
<h2>제약과 판독법</h2><ul><li>내장 원본 35장은 모두 배경이 있는 그림입니다. OPAQUE_SPRITE는 예상되는 입력 거부이며 실제 게임에서 해당 원본을 그대로 입상으로 쓴다는 증거는 아닙니다.</li><li>FRAME_GEOMETRY_OK는 기하 검사 결과입니다. 신원·의상·그림 품질·인물 간 시각적 크기가 정확하다는 보장은 아닙니다.</li><li>가상 바닥은 실제 함수와 CSS가 사용하는 허벅지 아래 가상 다리 길이 기준입니다. 그림에 발이 없어 실제 발 위치는 측정할 수 없습니다.</li><li>얼굴·머리 추정 실패와 원본에서 잘린 머리는 별도 실패로 남습니다. 화면 아래 몸통 잘림은 중간 거리 입상의 정상 구도와 구별해야 합니다.</li><li>iframe 뷰포트는 레이아웃 검사입니다. 실제 iPhone Safari·PWA 성능이나 safe-area 동작을 검증한 것은 아닙니다.</li><li>운영 보정 공식, 배포, API 키, 플레이 기록 및 기존 그림은 변경하지 않았습니다. 생산 소스 diff는 provenance.json에 보존합니다.</li><li>초기 테스트 도구의 임시 URL 보관/CSP 오류는 별도 파일로 보존했고 최종 결과와 분리했습니다.</li></ul>
<h2>자료</h2><p><a href="results/measurements.csv">전체 측정 CSV</a> · <a href="results/invariance.csv">크롭·해상도 편차 CSV</a> · <a href="results/analysis.json">집계 JSON</a> · <a href="results/measurements.json">원시 측정 JSON</a> · <a href="results/height-fixtures.json">김서연 포함 키 투영</a> · <a href="results/provenance.json">소스·도구·테스트 출처</a> · <a href="manifest.json">이미지 출처/키 설정</a></p>
<p>35명 단독 배치 연락판: <a href="rendered-contact-1.png">1–12</a> · <a href="rendered-contact-2.png">13–24</a> · <a href="rendered-contact-3.png">25–35</a></p>
<h2>인물별 실제 보정 결과</h2><p>PNG는 브라우저가 실제 CSS로 계산한 이미지 사각형으로 내보낸 비교판입니다. 격자·애니메이션·어두워짐 효과를 재현한 스크린샷과는 구분합니다. 노란 선은 자동 눈높이, 청록 선은 직접 기록한 눈높이/얼굴 폭입니다.</p>
${m.rows.filter(x=>m.eligible.includes(x.key)).map(row=>`<details><summary>${esc(row.title+' · '+row.person.name+' · '+row.heightCm+'cm')}</summary><div class="grid"><figure><img loading="lazy" src="${esc(row.reference.url.replace('/data/',''))}"><figcaption>내장 참조 원본</figcaption></figure><figure><img loading="lazy" src="generated/${esc(row.key)}.png"><figcaption>생성 원본 (미보정)</figcaption></figure></div>${['1440x900','844x390','390x844'].map(v=>`<h3>${v}</h3><div class="grid">${[1,3].map(n=>`<figure><img loading="lazy" src="results/${esc(row.key)}--generated--${v}--group-${n}.png"><figcaption>${n}인 배치</figcaption></figure>`).join('')}</div>`).join('')}</details>`).join('')}
<p><small>기존 회귀 테스트: 카메라·진입 관련 10/10 통과. 실제 육안 검토 결론은 visual-review.txt 참조. 이 문서의 자동 집계만으로 최종 육안 품질을 승인하지 않습니다.</small></p></html>`;
await fs.writeFile(path.join(root,'report.html'),html);console.log(JSON.stringify({...measurements,invariance:undefined,placement:undefined,soloMulti:undefined,works:undefined,manual},null,2));
