import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {webcrypto} from 'node:crypto';
import ts from 'typescript';
import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
import {JSDOM} from 'jsdom';
import * as liveWire from '../lib/multiplayer-live-wire';
import * as liveStore from '../lib/multiplayer-live';
import * as liveTiming from '../lib/multiplayer-live-timing';
import * as draftQueue from '../lib/multiplayer-draft-queue';
import * as reliability from '../lib/reader-reliability';

for(const mode of ['novel','visual'])test(mode+' player isolates chat from story loading, pauses hidden polling and preserves compact-media negotiation',async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://multiplayer.test/multiplayer/play?room=ABCDEF',pretendToBeVisual:true});
 const previousWindow=globalThis.window,previousDocument=globalThis.document;
 Object.assign(globalThis,{window:dom.window,document:dom.window.document,IS_REACT_ACT_ENVIRONMENT:true});
 const intervals=new Map<number,{fn:()=>void;ms:number}>(),requests:any[]=[],posts:any[]=[];
 const timeouts=new Map<number,{fn:()=>void;ms:number}>();
 let nextTimer=0,visible='visible',delay:Promise<void>|undefined,now=Date.now();
 class ClockDate extends Date {static now(){return now}}
 Object.defineProperty(dom.window.document,'visibilityState',{get:()=>visible});
 const room={code:'ABCDEF',status:'ACTIVE',isHost:true,currentMemberId:'self',turnDeadlineAt:new Date(Date.now()+120000).toISOString(),settings:{engine:'cortex',presentation:mode},members:[{id:'self',isSelf:true,displayName:'Test',status:'READY'}]};
 const envelope:any={room,cortex:{revision:1,turn:0,generating:false},snapshotVersion:'snapshot-one',mediaVersion:'media-one',snapshot:{schema:'CORTEX_TEST',turns:[],media:{packageAssets:[]}},messages:[]};
 const fetch=async(url:string,options:any={})=>{const body=options.body?JSON.parse(options.body):null;requests.push({url,body});if(delay)await delay;if(body?.action==='commit')envelope.cortex.revision++;return {ok:true,json:async()=>url==='/api/account'?{id:'test-account',authenticated:true}:url.endsWith('/cortex')?{revision:envelope.cortex.revision,mediaVersion:'media-one',snapshotVersion:'own-snapshot'}:url.includes('&base=')&&envelope.update?{...envelope,snapshot:undefined}:{...envelope,update:undefined}}};
 const require=createRequire(import.meta.url),exports:any={};
 const source=fs.readFileSync('app/multiplayer/play/page.tsx','utf8');
 const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 vm.runInNewContext(compiled,{exports,require:(name:string)=>{
  if(name.includes('text-provider'))return {deviceTextProvider:()=> 'opencode-go',deviceMuseReasoningEffort:()=> 'high'};
  if(name.includes('reader-device-preferences'))return {readerDevicePreferences:()=>({theme:'dark',fontSize:'medium',readingWidth:'wide',typingSpeed:'slow'})};
  if(name.includes('reader-reliability'))return reliability;
  if(name.includes('api-key-vault'))return {restoreRememberedApiKey:async()=> 'fake-key',rememberApiKeyOnDevice:async()=>{}};
  if(name.includes('room-chat'))return {RoomChat:(props:any)=>props.open?React.createElement('div',{role:'dialog'},React.createElement('button',{onClick:props.onClose},'대화 닫기')):null};
  if(name.includes('player-key-dialog'))return {PlayerKeyDialog:()=>null};
  if(name.includes('room-settings-dialog'))return {RoomSettingsDialog:(props:any)=>props.open?React.createElement('div',{role:'dialog'},React.createElement('button',{onClick:async()=>{await props.onSave(300);props.onClose();}},'멀티 설정 저장')):null};
  if(name.includes('use-press-feedback'))return {useMultiplayerPressFeedback:()=>{}};
  if(name.includes('multiplayer-live-wire'))return liveWire;
  if(name.includes('multiplayer-draft-queue'))return draftQueue;
  if(name.includes('multiplayer-live-timing'))return {...liveTiming,scheduleRoomPoll:(work:any,delay:any,visible:any)=>liveTiming.scheduleRoomPoll(work,delay,visible,{set:((fn:()=>void,ms:number)=>{timeouts.set(++nextTimer,{fn,ms});return nextTimer}) as any,clear:((id:number)=>timeouts.delete(id)) as any})};
  if(name.includes('multiplayer-live'))return liveStore;
  return require(name);
 },Date:ClockDate,window:dom.window,navigator:dom.window.navigator,document:dom.window.document,location:dom.window.location,crypto:webcrypto,performance,URLSearchParams,AbortSignal,fetch,console,setInterval:(fn:()=>void,ms:number)=>{intervals.set(++nextTimer,{fn,ms});return nextTimer},clearInterval:(id:number)=>intervals.delete(id)});
 const root=createRoot(dom.window.document.getElementById('root')!);
 try{
  await act(async()=>{root.render(React.createElement(exports.default))});
  const frame=dom.window.document.querySelector('iframe')!;
  assert.equal(new URL(frame.src).searchParams.get('view'),mode);
  frame.contentWindow!.postMessage=(data:any)=>{posts.push(data)};
  const message=(data:any)=>act(async()=>{dom.window.dispatchEvent(new dom.window.MessageEvent('message',{origin:dom.window.location.origin,source:frame.contentWindow,data:{channel:'NEXUS_CORTEX_HOST_V1',...data}}))});
  await message({type:'READY',sharedUpdates:true});
  assert.equal(requests.filter(r=>r.url.includes('?story=0&liveAfter=')).length,1);
  assert.equal(requests.filter(r=>r.url.includes('/chat')).length,1);
  assert.equal(posts.find(p=>p.type==='CLOUD_RESTORE').reuseMedia,false);
  assert.equal(posts.filter(p=>p.type==='MP_CONNECTION').at(-1).phase,'catching-up');
  await message({type:'CLOUD_RESTORE_COMPLETE'});
  assert.equal(posts.filter(p=>p.type==='MP_CONNECTION').at(-1).phase,'connected');
  await act(async()=>dom.window.dispatchEvent(new dom.window.Event('offline')));
  assert.equal(posts.filter(p=>p.type==='MP_CONNECTION').at(-1).phase,'offline');
  assert.equal(posts.filter(p=>p.type==='MP_STATE').at(-1).canWrite,false);
  await act(async()=>dom.window.dispatchEvent(new dom.window.Event('online')));
  assert.equal(posts.filter(p=>p.type==='MP_CONNECTION').at(-1).phase,'connected');
  room.members.push({id:'other',isSelf:false,displayName:'친구',status:'READY'});
  room.currentMemberId='other';
  await act(async()=>{[...intervals.values()].filter(x=>x.ms===1000).forEach(x=>x.fn())});
  assert.match(posts.filter(p=>p.type==='MP_STATE').at(-1).label,/친구의 차례 · \d+초/);
  assert.equal(posts.filter(p=>p.type==='MP_STATE').at(-1).canWrite,false);
  room.currentMemberId='self';
  assert.equal(timeouts.size,2);assert.ok([...timeouts.values()].some(x=>x.ms===1200),'closed chat rides the lightweight status cadence');
  const polls=[{fn:()=>{for(const row of [...timeouts.entries()]){timeouts.delete(row[0]);row[1].fn()}}}];
  assert.equal(posts.filter(p=>p.type==='MP_CHAT_PREVIEWS'&&p.messages.length).length,0,'initial history has no previews');
  envelope.messages=[{seq:1,name:'친구',body:'새 대화',isSelf:false,createdAt:new Date(Date.now()-60000).toISOString()},{seq:2,name:'나',body:'내 대화',isSelf:true,createdAt:new Date().toISOString()}];
  await act(async()=>{polls[0].fn()});
  assert.deepEqual(posts.filter(p=>p.type==='MP_CHAT_PREVIEWS').at(-1).messages.map((m:any)=>m.seq),[1]);
  const previews=posts.filter(p=>p.type==='MP_CHAT_PREVIEWS'&&p.messages.length).length;
  await act(async()=>{polls[0].fn()});assert.equal(posts.filter(p=>p.type==='MP_CHAT_PREVIEWS'&&p.messages.length).length,previews);
  await message({type:'MP_CHAT'});assert.ok(dom.window.document.querySelector('[role=dialog]'));
  assert.equal(posts.filter(p=>p.type==='MP_CHAT_OPEN').at(-1).open,true);
  await act(async()=>{(dom.window.document.querySelector('[role=dialog] button') as HTMLButtonElement).click()});
  assert.equal(dom.window.document.querySelector('[role=dialog]'),null);assert.ok(posts.some(p=>p.type==='MP_FOCUS_CHAT'));
  assert.equal(posts.filter(p=>p.type==='MP_CHAT_OPEN').at(-1).open,false);
  await message({type:'MP_SETTINGS'});assert.ok(dom.window.document.querySelector('[role=dialog]'));
  await act(async()=>{(dom.window.document.querySelector('[role=dialog] button') as HTMLButtonElement).click()});
  assert.ok(requests.some(r=>r.body?.action==='turn_limit'&&r.body.turnLimitSeconds===300));
  assert.equal(dom.window.document.querySelector('[role=dialog]'),null);
  envelope.cortex.generating=true;envelope.live={baseRevision:1,id:'live-one',seq:1,input:'',blocks:[{kind:'text',text:'함께 읽는 중'}]};
  await act(async()=>{polls[0].fn();await new Promise(resolve=>setTimeout(resolve,20))});assert.equal(posts.filter(p=>p.type==='MP_LIVE').length,1);assert.ok([...timeouts.values()].some(x=>x.ms===800));
  await act(async()=>{polls[0].fn();await new Promise(resolve=>setTimeout(resolve,20))});assert.equal(posts.filter(p=>p.type==='MP_LIVE').length,2,'unacknowledged iframe delivery is retried without reloading');
  await message({type:'MP_LIVE_RECEIVED',id:'live-one',seq:1});
  envelope.live={baseRevision:1,unchanged:true};await act(async()=>{polls[0].fn()});assert.equal(posts.filter(p=>p.type==='MP_LIVE').length,2);
  assert.ok(requests.some(r=>r.url.includes('liveAfter=1&liveId=live-one')));
  const clearCount=posts.filter(p=>p.type==='MP_LIVE_CLEAR').length;envelope.live=null;await act(async()=>{polls[0].fn()});assert.equal(posts.filter(p=>p.type==='MP_LIVE_CLEAR').length,clearCount,'missing frame during commit/upload race preserves the painted stream');
  envelope.cortex.generating=false;await act(async()=>{polls[0].fn()});assert.ok(posts.some(p=>p.type==='MP_LIVE_CLEAR'));
  const before=requests.length;visible='hidden';await act(async()=>{polls[0].fn()});assert.equal(requests.length,before);
  visible='visible';let release!:()=>void;delay=new Promise(resolve=>{release=resolve});
  await act(async()=>{dom.window.document.dispatchEvent(new dom.window.Event('visibilitychange'));polls[0].fn()});assert.equal(requests.length,before+1,'healthy closed chat uses the status response');
  now+=2000;await act(async()=>{polls[0].fn()});assert.equal(requests.length,before+2,'stalled status must not starve chat');
  await act(async()=>{delay=undefined;release()});
  const fullBefore=posts.filter(p=>p.type==='CLOUD_RESTORE').length;
  envelope.cortex.revision=2;envelope.snapshotVersion='snapshot-two';envelope.update={schema:'CORTEX_SHARED_UPDATE_V1',baseRevision:1,revision:2,operations:[]};
  await act(async()=>{polls[0].fn()});assert.ok(requests.some(r=>r.url.includes('&base=1&snapshotVersion=snapshot-one')));assert.equal(posts.filter(p=>p.type==='SHARED_UPDATE').length,1);assert.equal(posts.filter(p=>p.type==='CLOUD_RESTORE').length,fullBefore);
  await message({type:'MP_REQUEST',input:'반영 중 입력',autoContinue:false});assert.ok(!posts.some(p=>p.type==='MP_EXECUTE'));
  await message({type:'SHARED_UPDATE_COMPLETE',revision:2});
  envelope.cortex.revision=3;envelope.snapshotVersion='snapshot-three';envelope.update={schema:'CORTEX_SHARED_UPDATE_V1',baseRevision:2,revision:3,operations:[]};
  await act(async()=>{polls[0].fn()});await message({type:'SHARED_UPDATE_FAILED',message:'base mismatch'});
  assert.equal(posts.filter(p=>p.type==='CLOUD_RESTORE').length,fullBefore+1,'failed incremental application falls back once');
  await message({type:'CLOUD_RESTORE_COMPLETE'});
  if(mode==='visual'){
   await message({type:'MP_REQUEST',input:'아직 함께 읽는 중',autoContinue:false});assert.ok(!posts.some(p=>p.type==='MP_EXECUTE'),'writer cannot start while the room is still reading');
   envelope.playback={seq:1,turnId:'opening',start:0,startsAt:0,phase:'choices'};
   await act(async()=>{polls[0].fn()});
   assert.equal(posts.filter(p=>p.type==='MP_PLAYBACK').at(-1).playback.phase,'choices');
  }
  await message({type:'MP_REQUEST',input:'이어지는 행동',autoContinue:false});
  const execute=posts.find(p=>p.type==='MP_EXECUTE');assert.ok(execute);assert.equal(execute.compactMedia,true);
  assert.equal(requests.find(r=>r.body?.action==='begin').body.input,'이어지는 행동','publish input in the accepted begin request, before model execution');
  await message({type:'MP_LIVE_PUBLIC',token:'foreign-token',presentation:{seq:1}});assert.equal(requests.filter(r=>r.url.endsWith('/live')).length,0);
  let finishLive!:()=>void;delay=new Promise(resolve=>{finishLive=resolve});
  await message({type:'MP_LIVE_PUBLIC',token:execute.token,presentation:{id:'own-beat',input:'',seq:1,blocks:[]}});
  await message({type:'MP_LIVE_PUBLIC',token:execute.token,presentation:{id:'own-beat',input:'',seq:2,blocks:[]}});
  await message({type:'MP_LIVE_PUBLIC',token:execute.token,presentation:{id:'own-beat',input:'',seq:3,blocks:[]}});
  assert.equal(requests.filter(r=>r.url.endsWith('/live')).length,1,'coalesce while network is slow');
  await act(async()=>{delay=undefined;finishLive()});
  assert.equal(requests.filter(r=>r.url.endsWith('/live')).at(-1).body.presentation.seq,3,'newest queued frame starts immediately without the 800ms retry timer');
  await act(async()=>{[...intervals.values()].find(x=>x.ms===800)!.fn()});
  assert.equal(requests.filter(r=>r.url.endsWith('/live')).at(-1).body.presentation.seq,3,'send newest frame, not a backlog');
  await message({type:'MP_RESULT',token:execute.token,mediaUnchanged:true,snapshot:{schema:'CORTEX_TEST',turns:[{text:'다음 본문'}]}});
  const commit=requests.find(r=>r.body?.action==='commit');assert.equal(commit.body.mediaUnchanged,'media-one');assert.equal(commit.body.snapshot.media,undefined);
  assert.ok(posts.some(p=>p.type==='MP_COMMITTED'&&p.snapshotVersion==='own-snapshot'&&p.revision===4));
  const liveRequests=requests.filter(r=>r.url.endsWith('/live')).length;await act(async()=>{[...intervals.values()].find(x=>x.ms===800)!.fn()});assert.equal(requests.filter(r=>r.url.endsWith('/live')).length,liveRequests,'stop publishing after commit');
  for(const settings of posts.filter(p=>p.type==='SETTINGS')){assert.equal(settings.theme,'dark');assert.equal(settings.fontSize,'medium');assert.equal(settings.provider,'opencode-go');assert.equal(settings.museReasoningEffort,'high');}
  assert.equal(posts.filter(p=>p.type==='SETTINGS').at(-1).apiKey,mode==='visual'?'fake-key':'');
 }finally{await act(async()=>root.unmount());assert.equal(intervals.size,0);assert.equal(timeouts.size,0);dom.window.close();Object.assign(globalThis,{window:previousWindow,document:previousDocument,IS_REACT_ACT_ENVIRONMENT:false})}
});
