"use client";
import {useState} from 'react';
import {Area,Field,Panel,Select,Toggle} from './studio-sections';
import {blankStoryEvent,uid,type Project,type StoryEvent} from './studio-model';
import {eventDesign} from './cortex-event-design';
import {canonDesign,emptyCanonEvent,type CanonEventSettings} from './canon-design';

export function CanonEventsEditor({project:p,setProject,notify}:{project:Project;setProject:React.Dispatch<React.SetStateAction<Project>>;notify:(s:string)=>void}){
 const d=canonDesign(p),[collapsed,setCollapsed]=useState<string[]>([]);
 const edit=(id:string,patch:Partial<CanonEventSettings>)=>setProject(q=>{const a=canonDesign(q);return {...q,canonDesign:{...a,events:{...a.events,[id]:{...emptyCanonEvent(a.routes[0]?.id),...a.events[id],...patch}}}}});
 const change=(id:string,patch:Partial<StoryEvent>)=>setProject(q=>({...q,events:q.events.map(e=>e.id===id?{...e,...patch}:e)}));
 const routes=d.mode==='single'?d.routes.slice(0,1):d.routes;
 const add=(routeId:string)=>{const e={...blankStoryEvent(p.events.length+1),id:uid('EVENT'),required:true};setProject(q=>{const a=canonDesign(q);return {...q,events:[...q.events,e],canonDesign:{...a,events:{...a.events,[e.id]:emptyCanonEvent(routeId)}}}});};
 const remove=(id:string)=>{if(!confirm('이 사건을 삭제할까요? 연결된 분기와 복선은 다시 확인해야 합니다.'))return;setProject(q=>{const a=canonDesign(q),events={...a.events};delete events[id];return {...q,events:q.events.filter(e=>e.id!==id),canonDesign:{...a,events}}});};
 return <div className="canon-events">
 {d.migrationNotes?.length ? <Panel title="이전 작품에서 옮긴 설정"><ul>{d.migrationNotes.map((n,i)=><li key={i}>{n}</li>)}</ul><button className="soft-button" onClick={()=>setProject(q=>({...q,canonDesign:{...canonDesign(q),migrationNotes:[]}}))}>기존 설계 확인 완료</button></Panel>:null}<Panel title="이야기 구성"><Select label="루트 구성" value={d.mode} onChange={mode=>{if(mode==='single'&&d.routes.length>1&&!confirm('모든 사건을 하나의 루트로 합칩니다. 엔딩은 마지막 사건 하나로 정리합니다. 계속할까요?'))return;setProject(q=>{const a=canonDesign(q);return {...q,canonDesign:{...a,mode:mode as typeof a.mode,...(mode==='single'?{routes:a.routes.slice(0,1),events:Object.fromEntries(q.events.map((e,i)=>[e.id,{...emptyCanonEvent(),...a.events[e.id],routeId:a.routes[0].id,ending:i===q.events.length-1}]))}:{})}}})}} options={[{value:'single',label:'단일루트'},{value:'unlock',label:'엔딩 후 새로운 루트 해금'}]}/>
 {d.mode==='unlock'&&<><p>바로 앞 루트의 엔딩을 감상하면 다음 루트가 열립니다. 각 루트는 자체 시작 설정으로 시작합니다.</p><button className="soft-button" onClick={()=>setProject(q=>{const a=canonDesign(q);return {...q,canonDesign:{...a,routes:[...a.routes,{id:uid('ROUTE'),name:`${a.routes.length+1}번째 이야기`}]}}})}>＋ 루트 추가</button></>}
 </Panel>
 {routes.map((route,ri)=>{const events=p.events.filter(e=>e.kind!=='constraint'&&(d.mode==='single'||d.events[e.id]?.routeId===route.id)),ending=events.find(e=>d.events[e.id]?.ending),closed=collapsed.includes(route.id);return <section className="canon-route" key={route.id}>
 <header className="canon-route-head"><div><b>{route.name}</b><small>사건 {events.length}개 · {ending?'엔딩 지정됨':'작성 중'}{ri>0?` · ${routes[ri-1].name} 감상 후 열림`:''}</small></div><button className="soft-button" aria-expanded={!closed} onClick={()=>setCollapsed(closed?collapsed.filter(x=>x!==route.id):[...collapsed,route.id])}>{closed?'루트 펼치기':'루트 접기'}</button></header>
 {!closed&&<><Field label="루트 이름" value={route.name} onChange={name=>setProject(q=>{const a=canonDesign(q);return {...q,canonDesign:{...a,routes:a.routes.map(r=>r.id===route.id?{...r,name}:r)}}})} placeholder="첫 번째 이야기"/>
 {!events.length&&ri>0&&<button className="soft-button danger-button" onClick={()=>setProject(q=>{const a=canonDesign(q);return {...q,canonDesign:{...a,routes:a.routes.filter(r=>r.id!==route.id)}}})}>빈 루트 삭제</button>}
 {events.map((e,index)=>{const c={...emptyCanonEvent(route.id),...d.events[e.id]},ed=eventDesign(e),design=(patch:Partial<typeof ed>)=>change(e.id,{cortexDesign:{...ed,...patch}}),targets=[{value:'',label:'사건 선택'},...events.filter(x=>x.id!==e.id&&x.kind!=='constraint').map(x=>({value:x.id,label:x.name}))];
 return <Panel key={e.id} title={`${index+1}. ${e.name}`} actions={<div className="page-actions"><button className="soft-button" disabled={index===0||!!ending} onClick={()=>setProject(q=>{const arr=[...q.events],i=arr.findIndex(x=>x.id===e.id),j=arr.findIndex(x=>x.id===events[index-1].id);[arr[i],arr[j]]=[arr[j],arr[i]];return {...q,events:arr}})}>위로</button><button className="soft-button danger-button" onClick={()=>remove(e.id)}>삭제</button></div>}>
 {index===0&&d.mode==='unlock'&&<><Select label="이 루트의 시작 사건" value={route.id} options={d.routes.filter(r=>r.id===route.id||!p.events.some(x=>d.events[x.id]?.routeId===r.id)).map(r=>({value:r.id,label:r.name}))} onChange={routeId=>{for(const x of events)edit(x.id,{routeId})}}/><Area label="시작 전 작가 코멘트 · 선택" value={c.authorComment} onChange={authorComment=>edit(e.id,{authorComment})} placeholder="이번 이야기는 첫 번째 루트와 다른 선택에서 출발합니다. 시간은 입학 첫날로 돌아가며 인물들은 이전 루트의 일을 기억하지 못합니다."/></>}
 <Field label="사건 이름" value={e.name} onChange={name=>change(e.id,{name})} placeholder="사라진 학생의 방"/>
 <div className="trigger-options"><Toggle label="필수사건" checked={e.required} onChange={required=>change(e.id,{required})}/><Toggle label="주인공 이외 인물 시점" checked={ed.otherViewpoint} onChange={otherViewpoint=>design({otherViewpoint})}/><Toggle label="발생조건" checked={ed.occurrenceEnabled} onChange={occurrenceEnabled=>design({occurrenceEnabled})}/></div>
 {ed.otherViewpoint&&<Field label="시점 인물과 의도" value={ed.viewpoint} onChange={viewpoint=>design({viewpoint})} placeholder="레나의 시점. 주인공이 모르는 조사 과정을 보여준다."/>}
 {ed.occurrenceEnabled&&<Area label="발생조건" value={ed.occurrence} onChange={occurrence=>design({occurrence})} placeholder="주인공이 학생회의 조사 의뢰를 받아들인 경우에만 발생한다."/>}
 <Area label="사건 내용" value={e.description} onChange={description=>change(e.id,{description})} placeholder="기숙사 205호에서 레나와 실종 사건을 조사한다. 창문은 안에서 잠겨 있고 책상에는 학생증이 남아 있다."/>
 <div className="cortex-closure-box"><h3>종결조건</h3>{ed.closureConditions.map((r,i)=><div key={r.id}><Area label={`조건 ${i+1}`} value={r.text} onChange={text=>design({closureConditions:ed.closureConditions.map(x=>x.id===r.id?{...x,text}:x)})} placeholder="독자가 잠긴 금고 안에 아무것도 없다는 사실을 확인한다."/><button className="soft-button" onClick={()=>design({closureConditions:ed.closureConditions.filter(x=>x.id!==r.id)})}>조건 삭제</button></div>)}<button className="soft-button" onClick={()=>design({closureConditions:[...ed.closureConditions,{id:uid('CONDITION'),text:''}]})}>＋ 종결조건</button></div>
 <Toggle label="분기 사용" checked={c.branching} onChange={branching=>edit(e.id,{branching,ending:branching?false:c.ending})}/>
 {c.branching&&<div className="canon-card"><p>위에서부터 처음 충족한 조건의 사건으로 이어집니다.</p>{c.branches.map((b,bi)=>{const patch=(v:Partial<typeof b>)=>edit(e.id,{branches:c.branches.map(x=>x.id===b.id?{...x,...v}:x)});return <article className="canon-branch" key={b.id}><Select label={`분기 ${bi+1} · 판단 방식`} value={b.kind} onChange={kind=>patch({kind:kind as typeof b.kind})} options={[{value:'story',label:'이야기 내용'},{value:'stat',label:'스탯·자원 수치'}]}/>{b.kind==='story'?<Area label="분기 조건" value={b.criterion} onChange={criterion=>patch({criterion})} placeholder="주인공이 레나의 비밀을 다른 사람에게 알리지 않고 지켜주었다."/>:<div className="canon-values"><Select label="수치" value={b.statId} onChange={statId=>patch({statId})} options={[{value:'',label:'수치 선택'},...d.stats.map(s=>({value:s.id,label:s.label}))]}/><Select label="비교" value={b.comparison} onChange={comparison=>patch({comparison:comparison as typeof b.comparison})} options={[{value:'gte',label:'이상'},{value:'lt',label:'미만'}]}/><Field label="기준값" type="number" value={b.threshold} onChange={v=>patch({threshold:Number(v)})}/></div>}<Select label="이어질 사건" value={b.nextEventId} options={targets} onChange={nextEventId=>patch({nextEventId})}/><button className="soft-button" disabled={!bi} onClick={()=>{const a=[...c.branches];[a[bi-1],a[bi]]=[a[bi],a[bi-1]];edit(e.id,{branches:a})}}>우선순위 올리기</button><button className="soft-button danger-button" onClick={()=>edit(e.id,{branches:c.branches.filter(x=>x.id!==b.id)})}>분기 삭제</button></article>})}<button className="soft-button" onClick={()=>edit(e.id,{branches:[...c.branches,{id:uid('CHOICE'),kind:'story',criterion:'',statId:'',threshold:60,comparison:'gte',nextEventId:''}]})}>＋ 분기 추가</button><Select label="해당 조건이 없거나 판정할 수 없을 때" value={c.fallbackEventId} options={targets} onChange={fallbackEventId=>edit(e.id,{fallbackEventId})}/><p>판정 불가를 실패로 꾸미지 않고 기본 경로로 이어집니다.</p></div>}
 {!c.branching&&!c.ending&&<Select label="다음 사건" value={e.nextEventId} options={[{value:'',label:'목록 순서대로'},...targets.slice(1)]} onChange={nextEventId=>change(e.id,{nextEventId})}/>}
 <details className="jieum-extra"><summary>제약·대체 종결 · 선택</summary><Area label="장면 제약" value={ed.constraints} onChange={constraints=>design({constraints})} placeholder="플레이어의 대답을 대신 정하지 않는다."/><Area label="허용할 대체 종결" value={ed.unmet} onChange={unmet=>design({unmet})} placeholder="금고를 열지 못했다면 관리인의 증언으로 빈 금고였음을 확인할 수 있다."/></details>
 <details className="jieum-extra" open={c.effects.length>0||undefined}><summary>점수 변화 · 선택</summary><p>조건마다 사건당 한 번 적용합니다. 감소는 음수로 입력하세요.</p>{c.effects.map(ef=>{const patch=(v:Partial<typeof ef>)=>edit(e.id,{effects:c.effects.map(x=>x.id===ef.id?{...x,...v}:x)});return <div className="canon-card" key={ef.id}><Area label="점수가 변하는 조건" value={ef.criterion} onChange={criterion=>patch({criterion})} placeholder="주인공이 레나의 비밀을 지켰다."/><Select label="변경할 점수" value={ef.statId} options={[{value:'',label:'점수 선택'},...d.stats.filter(s=>s.mode==='event').map(s=>({value:s.id,label:s.label}))]} onChange={statId=>patch({statId})}/><Field label="변화량" type="number" value={ef.amount} onChange={v=>patch({amount:Number(v)})}/><button className="soft-button danger-button" onClick={()=>edit(e.id,{effects:c.effects.filter(x=>x.id!==ef.id)})}>변화 삭제</button></div>})}<button className="soft-button" onClick={()=>edit(e.id,{effects:[...c.effects,{id:uid('SCORE'),criterion:'',statId:'',amount:10}]})}>＋ 점수 변화</button></details>
 <div className="canon-ending"><Toggle label="이 사건으로 루트 종료" checked={c.ending} onChange={ending=>{if(ending&&index!==events.length-1){notify('루트의 마지막 사건에서 엔딩을 지정하세요.');return;}setProject(q=>{const a=canonDesign(q);return {...q,canonDesign:{...a,events:{...a.events,...Object.fromEntries(events.map(x=>[x.id,{...emptyCanonEvent(route.id),...a.events[x.id],ending:x.id===e.id?ending:false,...(x.id===e.id&&ending?{branching:false}:{})}]))}}}})}}/><p>이 사건의 종결조건이 충족되면 엔딩이 확정됩니다.</p></div>
 </Panel>})}
 {!ending?<button className="primary-button" onClick={()=>add(route.id)}>＋ {events.length?'사건 추가':'시작 사건 추가'}</button>:<p className="canon-sample">루트가 완성되었습니다. 사건을 더 넣으려면 엔딩 토글을 해제하세요.</p>}
 </>}
 </section>})}
 </div>;
}
